apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-operators-application
spec:
  project: cluster
  source:
    repoURL: https://github.com/kubetrade/gitops-cluster.git
    targetRevision: HEAD
    path: openshift-operators
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false