apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sso-application
  namespace: openshift-gitops
spec:
  project: cluster
  source:
    repoURL: https://github.com/kubetrade/gitops-cluster.git
    targetRevision: HEAD
    path: sso
  destination:
    server: https://kubernetes.default.svc
    namespace: sso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true